name: jack_gen
description: Code Generation Package
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  analyzer: ">=4.7.0 <6.0.0"
  build: ^2.4.1
  source_gen: ^1.4.0


dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.6

